---
apiVersion: v1
kind: ReplicationController
metadata:
  name: configsvr
spec:
  replicas: 1
  selector:
    app: configsvr
  template:
    metadata:
      labels:
        app: configsvr
    spec:
      containers:
      - name: configsvr
        image: kadanli/configserver:v0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: configsvr
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: configsvr

